### ISSUE TITLE
position of mathjax elements change depending on whether parent detail tag is open or closed

### ISSUE THREAD

**Issue by NguyenVuKhang** [jsxgraph/jsxgraph#348] opened 2021-04-01 04:02 UTC
when a jsxgraph div is nested in a \<details\> tag, its mathjax elements' positions are slightly different based on if the details tag is open: `<details open>` or closed: `<details>`

consider the following minimal html file:
```
<head>
    <script type="text/javascript" charset="UTF-8" src="https://cdn.jsdelivr.net/npm/jsxgraph@1.1.0/distrib/jsxgraphcore.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/jsxgraph@1.1.0/distrib/jsxgraph.css" />

    <script type="text/javascript" id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
</head>
<body>
    <div id="box" class="jxgbox" style="margin:auto; width:24em; height:20em;"></div>
    <script type="text/javascript">
        var board = JXG.JSXGraph.initBoard('box', {boundingbox: [-10, 10, 10, -10], axis:true});
        graph_label = board.create('text', [0,0,
            function() {
                return '\\( y=mx+c \\)';
            }
        ], {useMathJax:true});
    </script>
    <details>
        <div id="box_details_closed" class="jxgbox" style="margin:auto; width:24em; height:20em;"></div>
        <script type="text/javascript">
            var board = JXG.JSXGraph.initBoard('box_details_closed', {boundingbox: [-10, 10, 10, -10], axis:true});
            graph_label = board.create('text', [0,0,
                function() {
                    return '\\( y=mx+c \\)';
                }
            ], {useMathJax:true});
        </script>
    </details>
    <details open>
        <div id="box_details_open" class="jxgbox" style="margin:auto; width:24em; height:20em;"></div>
        <script type="text/javascript">
            var board = JXG.JSXGraph.initBoard('box_details_open', {boundingbox: [-10, 10, 10, -10], axis:true});
            graph_label = board.create('text', [0,0,
                function() {
                    return '\\( y=mx+c \\)';
                }
            ], {useMathJax:true});
        </script>
    </details>
</body>
```
This file makes three identical instances of jsxgraph. They are different like so:

- first one is placed as child of `<body>`
- second one is placed as child of `<details>` (closed)
- third one is placed as child of `<details open>` (open)

this is the result, loaded in Safari:
![visual result](https://user-images.githubusercontent.com/10664455/113240924-400f3480-92e0-11eb-9f49-5ca5ac92c26e.png)

expected: for all the mathjax elements to be displayed the same
result: the mathjax element of the second instance of jsxgprah is displaced downwards slightly

upon using Safari's "inspect element" option, it can be seen that there are differences in the positioning functions:

child of `<body>`:
![body](https://user-images.githubusercontent.com/10664455/113241429-481ba400-92e1-11eb-931a-266596dbf0c1.png)

child of `<details>` (note that here it shows `<details open>` because I opened up the details field by clicking it to expand it.
![details closed](https://user-images.githubusercontent.com/10664455/113241423-4651e080-92e1-11eb-8492-d12b79f64b3e.png)

child of `<details open>`
![details open](https://user-images.githubusercontent.com/10664455/113241432-48b43a80-92e1-11eb-9176-29c791f071a2.png)

The difference is that the `top` attribute of class `JXGText` in the second code block is different.

I tried looking into the source code and doing a project search on JXGtext and reading the surrounding code but I still can't pinpoint why this issue occurs. Any help is greatly appreciated!

**Comment by alfredwassermann** [comment] 2021-05-21 08:15
Fixed by 52f7166. The fix will be available in v1.2.3.

The problem is that JSXGraph will not receive the (future) size of the text box if the parent element is hidden during board initialisation. To be specific: the browser will return [0,0] as size of the text box. With the fix in 52f7166, it is possible to at least add an event listener on the toggle event of the details tag and call board.fullUpdate(). This will resolve this issue.

This version will work with v1.2.3:

    <div id="box" class="jxgbox" style="margin:auto; width:24em; height:20em;"></div>
    <script type="text/javascript">
        var board1 = JXG.JSXGraph.initBoard('box', {boundingbox: [-10, 10, 10, -10], axis:true});
        var graph_label1 = board1.create('text', [0,0,
            function() {
                return '\\( y=mx+c \\)';
            }
        ], {useMathJax:true});
    </script>
    <details id="AAA">
        <div id="box_details_closed" class="jxgbox" style="margin:auto; width:24em; height:20em;"></div>
        <script type="text/javascript">
            var board2 = JXG.JSXGraph.initBoard('box_details_closed', {boundingbox: [-10, 10, 10, -10], axis:true});
            var graph_label2 = board2.create('text', [0,0,
                function() {
                    return '\\( y=mx+c \\)';
                }
            ], {useMathJax:true});

            document.getElementById("AAA").addEventListener("toggle", function() { board2.fullUpdate(); }); 
        </script>
    </details>
    <details open>
        <div id="box_details_open" class="jxgbox" style="margin:auto; width:24em; height:20em;"></div>
        <script type="text/javascript">
            var board3 = JXG.JSXGraph.initBoard('box_details_open', {boundingbox: [-10, 10, 10, -10], axis:true});
            var graph_label3 = board3.create('text', [0,0,
                function() {
                    return '\\( y=mx+c \\)';
                }
            ], {useMathJax:true});
        </script>
    </details>

**Closed by alfredwassermann** 2021-05-21 08:15 UTC
